name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC
  workflow_dispatch:       # Allows manual triggering for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp by 23f1002745@ds.study.iitm.ac.in
        run: |
          echo "Updated at $(date -u)" >> daily-log.txt
          git config --global user.name "devsync-bot"
          git config --global user.email "23f1002745@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily update: $(date -u)"
          git push
